### ISSUE TITLE
LINK

### ISSUE THREAD

**Issue by SHAKUURR** [f-lajoc/Zodiac-sign#1]
Hi, madam! 
Good job😋.... I'm excited seeing you doing this amazing stuff. However, the link in the acknowledgment is not directing to the main user. 

Here is the link original link to shakur's profile: https://github.com/SHAKUURR

Thank you..✊ Thanks for acknowledging me. You're motivating me to do more as a beginner.

**Comment by f-lajoc** [comment]
thanks for letting me know, I'll edit it right away
